gerber/__main__.py, gerber/common.py, gerber/render/__init__.py, gerber/tests/test_cam.py, gerber/tests/test_common.py, gerber/tests/test_primitives.py, gerber/tests/test_rs274x.py, setup.py
I found them when working on making the package Py3 compatible.
Those relative import statements seem to work fine on Py2.7 too.
=> Fixing more relative import statements

gerber/__main__.py
The statement `print >> sys.stderr` was not Python3 compatible.
=> Updating gerber/__main__.py for Python3

gerber/am_eval.py, gerber/am_read.py, gerber/am_statements.py, gerber/gerber_statements.py, gerber/rs274x.py, gerber/tests/test_gerber_statements.py
Aperture macros can get complex with arithmetical operations,
variables and variables substitution.
Current pcb-tools code just read each macro block as an independent
unit, this cannot deal with variables that get changed after used.
This patch splits the task in two: first we parse all macro content
and creates a bytecode representation of all operations. This bytecode
representation will be executed when an AD command is issues passing
the required parameters.
Parsing is heavily based on gerbv using a Shunting Yard approach to
math parsing.
Integration with rs274x.py code is not finished as I need to figure out
how to integrate the final macro primitives with the graphical primitives
already in use.
=> Add aperture macro parsing and evaluation.

gerber/excellon.py, gerber/primitives.py, gerber/rs274x.py, gerber/tests/test_primitives.py
Checking was happening at the gerber/excellon file level, but this adds units checking at the primitive level so the use case shown in the example is covered. Might want to throw a bunch more assertions in the test code (i started doing a few) to cover multiple calls to unit conversion functions
=> Fix for #25. Check units at the primitive level

examples/cairo_example.py, gerber/__init__.py, gerber/common.py, gerber/excellon.py, gerber/render/cairo_backend.py, gerber/render/render.py, gerber/rs274x.py, gerber/tests/test_common.py, gerber/tests/test_excellon.py, gerber/utils.py
Add ```loads()``` function to top-level gerber module, allowing ```GerberFile``` and ```ExcellonFile``` instances to be created from strings containing gerber file contents.
=> Read from memory

gerber/rs274x.py
I just hit a little issue that apertures aren't assigned a unit, so calling to_metric doesn't do anything. I hope this fixes it without breaking anything!
=> Make sure apertures get a unit

gerber/render/cairo_backend.py
This fixes a crash in cairocffi on Python3, and should be compatible
with both python2 and python3. In python2, byte strings are just
strings. In python3, when getting binary data, the user probably wants
a byte string instead of a regular string.
=> cairo_backend.py: use BytesIO instead of StringIO

gerber/render/cairo_backend.py, gerber/tests/test_cairo_backend.py
Python 3 fix for Cairo backend and SVG dumping.
Dumping of svg files is never tested. Added a basic test for this use case.
=> Fix Cairo backend for svg saving and Python 3

gerber/rs274x.py
In some cases, the computation of valid sweep angle hits numerical limits and no centers are found.
This PR adds a small amount of tolerance into the comparison.
=> Add tolerance to center finding

gerber/render/cairo_backend.py
I added a bounds argument to render_layer. The reason is that I want to render a single bitmap for every layer and process them together. The autoscaling of each layer was preventing the multiple bitmaps from lining up. I plan to use board bounds and layer bounds based on the board outline found in the board's IDF3 file.
=> Added bounds argument to render_layer()

gerber/rs274x.py
In Python 3, sys.maxint was removed, however its current use
can be safely substituted with sys.maxsize (also in Python 2)
See also: https://docs.python.org/3.1/whatsnew/3.0.html#integers
=> Add GerberParser fix for Python 3.x

.travis.yml, gerber/utils.py, requirements.txt, setup.py
I added a python implementation of quickhull to provide the convex hull functionality that is the only reason we pull in scipy. This allows us to not be dependent on scipy, which is very large and has many dependencies of its own.
=> Remove dependency on scipy by adding quickhull implementation to utils

gerber/gerber_statements.py, gerber/render/cairo_backend.py
I just stumbled upon these while trying out pcb-tools.
=> Add hole support to ADParamStmt.rect and fix cairocffi compatibility

gerber/pcb.py
If you try to import a directory that contains subdirectories it fails and throws an exception.
=> Skip subdirectories during import

gerber/layers.py, gerber/tests/test_layers.py
Regular expressions only matched the base name. This matches the entire filename which allows for more advanced regular expressions.
=> Match full filename instead of the base name

gerber/render/cairo_backend.py
For some reason, copy.copy would barf saying it can't deep copy cairo
matrices. I'm using python 3.6.5 and cairocffi 0.7.2 on Fedora 28.
This PR just replaces the deep copy call with a multiplication by a unity matrix, having the same effect.
=> Fix cairo matrix clone op to not use copy.copy

gerber/excellon_statements.py, gerber/utils.py
Hello,
This PR replaces PR#103 with a more efficient and retro-compatible implementation.
This PR does two things:
1) pairwise function is now compatible with 3.7 as well as all tested python versions
2) Allow the use of float format in FileSettings:
Use:
fs = FileSettings(units="metric", zeros="trailing", format=(float,3))
This configuration will be used in writer_gerber_value to use a float representation.
Why ? Most tools are now compatible with floats in excellon files, and this allows the use of larger PCB, especially in the case of panelized PCBs using opiopan's library.
I only changed the first element of the format tupple for two reasons:
* It is very compatible with the rest of the code (no modifications other than the intended one)
* Tools configuration still require the 3nd …
=> Allow float fmt and fix 3.7

gerber/layers.py, gerber/pcb.py
gEDA pcb generated gerbers have filenames which are not correctly recognized. This PR adds the necessary strings to the hints and some additional changes needed to correctly handle the gerber files and guess the PCB name correctly.
For reference, the following are the gerbers generated for a 4 layer PCB named "qmb":
```
$ ls -1
qmb.bottom.gbr
qmb.bottommask.gbr
qmb.bottompaste.gbr
qmb.bottomsilk.gbr
qmb.fab.gbr
qmb.group3.gbr
qmb.group4.gbr
qmb.outline.gbr
qmb.plated-drill.cnc
qmb.top.gbr
qmb.topmask.gbr
qmb.toppaste.gbr
qmb.topsilk.gbr
```
=> Correctly recognize gEDA pcb generated gerber filenames

setup.py
Every other reference to the license for this project states Apache 2.0, so I presume that it was a typo that "Apple Public Source" license was stated in the trove classifier?
- https://github.com/curtacircuitos/pcb-tools/blob/efb46c562cf1cfdf0f340cff81cea8bc06e97dc4/LICENSE#L1-L3
- https://github.com/curtacircuitos/pcb-tools/blob/efb46c562cf1cfdf0f340cff81cea8bc06e97dc4/setup.py#L30
=> Fix typo in license trove classifier

gerber/am_statements.py
Remove unit conversion since Polygon expects degree. This bug leads to false rotated polygons in aperture macros.
=> Bugfix for Polygon Aperture Macros
